#!/bin/sh
_pkg=$1
_path=/var/cache/pacman/pkg
_uninstall='sudo pacman -U'
if [ -z "$1" ]; then
	echo "Usage: $(basename "$0") <package> ..."
	exit
fi
last_pkg()
{
	find "$_path" -name "$_pkg-*.zst" | sort | tail -n2 | head -n1
}
for x in $@; do
	pkgs="$pkgs $(last_pkg "$x")"
done
$_uninstall $pkgs
